import type { Project } from "../../types";

export const projects: Project[] = [
  {
    id: "frame-os",
    name: "Frame OS",
    tagline: "AI-native application compositor. The shell that holds everything together.",
    url: "https://frame.jim.software",
    tags: ["module-federation", "react", "redux"],
    status: "live",
  },
  {
    id: "cv-builder",
    name: "CV Builder",
    tagline: "Resume generation with LangGraph agent orchestration and visual regression CI.",
    url: "https://cv.jim.software",
    tags: ["langgraph", "ai-agents", "playwright"],
    status: "live",
  },
  {
    id: "blogengine",
    name: "BlogEngine",
    tagline: "Multi-tab content dashboard with Notion integration and podcast responder.",
    url: "https://blog.jim.software",
    tags: ["notion-api", "langgraph", "sse"],
    status: "live",
  },
  {
    id: "tripplanner",
    name: "TripPlanner",
    tagline: "11-phase SSE pipeline. Six itinerary views. One question to plan a trip.",
    url: "https://trips.jim.software",
    tags: ["sse-pipeline", "langgraph", "sqlite"],
    status: "live",
  },
  {
    id: "core-reader",
    name: "Core Reader",
    tagline: "Self-documenting dashboard. ADRs and commands rendered from the filesystem.",
    url: "https://core-reader.jim.software",
    tags: ["chokidar", "filesystem", "read-only"],
    status: "live",
  },
  {
    id: "daily-logger",
    name: "Daily Logger",
    tagline: "Claude sweeps 11 repos nightly and publishes a development journal.",
    url: "https://log.jim.software",
    tags: ["automation", "github-api", "jekyll"],
    status: "live",
  },
  {
    id: "seh-study",
    name: "SEH Study",
    tagline: "Spaced repetition for 238 NASA SEH glossary terms. Leitner box algorithm.",
    url: "https://seh-study.jim.software",
    tags: ["spaced-repetition", "carbon", "education"],
    status: "live",
  },
  {
    id: "purefoy",
    name: "Purefoy",
    tagline: "Roger Deakins cinematography RAG. Where film theory meets machine learning.",
    url: "#",
    tags: ["python", "rag", "cinematography"],
    status: "coming-soon",
  },
  {
    id: "lean-canvas",
    name: "Lean Canvas",
    tagline: "AI-assisted 9-section business model canvas. Strategy as conversation.",
    url: "#",
    tags: ["langgraph", "business-modeling", "carbon"],
    status: "coming-soon",
  },
  {
    id: "gastown-pilot",
    name: "Gastown Pilot",
    tagline: "Six-tab governance simulation dashboard. Twelve panel stubs, three data adapters.",
    url: "#",
    tags: ["react-query", "simulation", "dashboard"],
    status: "coming-soon",
  },
];
