import type { Project } from "../../types";

export const projects: Project[] = [
  {
    id: "frame-os",
    name: "Frame OS",
    tagline: "AI-native application compositor. The shell that holds everything together.",
    url: "https://frame.jim.software",
    tags: ["module-federation", "react", "redux"],
    status: "live",
    preview: "/previews/frame-os.png",
    previewAlt: "Frame OS shell with module federation remotes",
  },
  {
    id: "cv-builder",
    name: "Resumé Builder",
    tagline: "Resume generation with LangGraph agent orchestration and visual regression CI.",
    url: "https://frame.jim.software?app=resume-builder",
    tags: ["langgraph", "ai-agents", "playwright"],
    status: "live",
    preview: "/previews/cv-builder.png",
    previewAlt: "Resumé Builder with LangGraph agent graph",
  },
  {
    id: "blogengine",
    name: "BlogEngine",
    tagline: "Multi-tab content dashboard with Notion integration and podcast responder.",
    url: "https://frame.jim.software?app=blogengine",
    tags: ["notion-api", "langgraph", "sse"],
    status: "live",
    preview: "/previews/blogengine.png",
    previewAlt: "BlogEngine multi-tab content dashboard",
  },
  {
    id: "tripplanner",
    name: "TripPlanner",
    tagline: "11-phase SSE pipeline. Six itinerary views. One question to plan a trip.",
    url: "https://frame.jim.software?app=tripplanner",
    tags: ["sse-pipeline", "langgraph", "sqlite"],
    status: "live",
    preview: "/previews/tripplanner.png",
    previewAlt: "TripPlanner itinerary view with SSE pipeline",
  },
  {
    id: "core-reader",
    name: "Core Reader",
    tagline: "The control surface — ADRs, commands, and project state rendered live from the filesystem. How 11+ apps and plugins stay legible.",
    url: "https://frame.jim.software?app=core-reader",
    tags: ["chokidar", "filesystem", "read-only"],
    status: "live",
    preview: "/previews/core-reader.png",
    previewAlt: "Core Reader ADR and command dashboard",
  },
  {
    id: "daily-logger",
    name: "Daily Logger",
    tagline: "The connective tissue — Claude sweeps 11+ repos and plugins nightly, tracks every roadmap, and publishes a development journal that keeps the whole fleet moving.",
    url: "https://log.jim.software",
    tags: ["automation", "github-api", "react", "vercel"],
    status: "live",
    preview: "/previews/daily-logger.png",
    previewAlt: "Daily Logger development journal",
  },
  {
    id: "seh-study",
    name: "SEH Study",
    tagline: "Spaced repetition for 238 NASA SEH glossary terms. Leitner box algorithm.",
    url: "https://frame.jim.software?app=seh-study",
    tags: ["spaced-repetition", "carbon", "education"],
    status: "live",
    preview: "/previews/seh-study.png",
    previewAlt: "SEH Study spaced repetition interface",
  },
  {
    id: "purefoy",
    name: "Purefoy",
    tagline: "RAG interface to the Team Deakins knowledge base. Ask questions, get sourced answers.",
    url: "https://frame.jim.software?app=purefoy",
    tags: ["python", "rag", "cinematography"],
    status: "live",
    preview: "/previews/purefoy.png",
    previewAlt: "Purefoy cinematography knowledge base",
  },
  {
    id: "tde",
    name: "Team Deakins Engine",
    tagline: "348 episodes. 3,000+ forum threads. Hit play on everything Roger Deakins.",
    url: "https://tde.jim.software",
    tags: ["sqlite-fts5", "carbon", "module-federation"],
    status: "live",
    preview: "/previews/tde.png",
    previewAlt: "Team Deakins Engine transcript editor interface",
  },
  {
    id: "lean-canvas",
    name: "Lean Canvas",
    tagline: "AI-assisted 9-section business model canvas. Strategy as conversation.",
    url: "https://frame.jim.software?app=lean-canvas",
    tags: ["langgraph", "business-modeling", "carbon"],
    status: "live",
    preview: "/previews/lean-canvas.png",
    previewAlt: "Lean Canvas business model editor",
  },
  {
    id: "gastown-pilot",
    name: "Gastown Pilot",
    tagline: "Six-tab governance simulation dashboard. Twelve panel stubs, three data adapters.",
    url: "https://frame.jim.software?app=gastown-pilot",
    tags: ["react-query", "simulation", "dashboard"],
    status: "live",
    preview: "/previews/gastown-pilot.png",
    previewAlt: "Gastown Pilot governance dashboard",
  },
  {
    id: "hailstone",
    name: "Hailstone",
    tagline: "Chuuk Lagoon wreck diving map. 3D Mapbox terrain, Firebase photo sharing, GSAP animations.",
    url: "https://hailstone.ocommaj.com",
    tags: ["mapbox-gl", "firebase", "gsap"],
    status: "live",
    preview: "/previews/hailstone.png",
    previewAlt: "Hailstone wreck diving map with 3D Mapbox terrain",
  },
];
